### ISSUE TITLE
Make Donor controlled

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1271]
Remediate Donor strings to URIs.

**Comment by sseymore** [comment]
UO remediation work is done. 

Dev work is needed to configure the field for URIs -- the existing URIs are still in raw statements.

**Comment by carakey** [comment]
OSU remediation progress:

- [ ] Search for name URIs and create new records as needed (spreadsheet work)
  - [ ] Columbia Gorge Discovery Center Photo Archive
  - [ ] Historic and Cultural Textile and Apparel Collection
  - [ ] Lincoln County Historical Society Archive
  - [ ] Oregon Hops & Brewing Archives
  - [ ] OSU SCARC
  - [ ] The Fairbanks Fine Arts Print Collection
  - [ ] The Middle East Water Collection
- [ ] Batch add new records to ONS
- [ ] Make scripted batch edits in OD
  - [ ] Change donor strings to URIs
  - [ ] Append non-URI donor info to descriptions

**Comment by carakey** [comment]
Broken out by collection, per Beth's request:

- [ ] Columbia Gorge Discovery Center Photo Archive #1320 
- [ ]  Historic and Cultural Textile and Apparel Collection #1321 
- [ ]  Lincoln County Historical Society Archive #1326 
- [ ]  Oregon Hops & Brewing Archives #1325 
- [ ]  OSU SCARC #1324 
- [ ]  The Fairbanks Fine Arts Print Collection #1323 
- [ ]  The Middle East Water Collection #1322

**Comment by carakey** [comment]
Closing this ticket / Tracking work on individual collection tickets.
