### ISSUE TITLE
UO metadata remediation needs

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#1274]
Need scrape from OD1:
- [ ] Create Date ranges to replace Earliest/Latest Dates #1259 
- [ ] Move Support property values to Material #1244 
- [ ] Orphan Works usage in OD1 #1263 
- [ ] British Museum vocab usage #1265 
- [ ] Change Publisher values to URIs, add Creator controlled vocabulary class to Publisher #898

Replace URIs with label strings:
- [ ] Make Rightsholder uncontrolled #1261 
- [ ] Make Copyright Claimant uncontrolled #1266 
- [ ] Make Contained In Journal uncontrolled #1267
- [ ] Make Location Copy--Shelf Location uncontrolled #1269
- [ ] Make Series Name uncontrolled #1270

Replace strings with URIs:
- [ ] Make Form of Work controlled #1272

Move data (do not remove predicate yet):
- [ ] Move Caption Title property values to Alternative Title #1246

Change predicate (move data to new predicate):
- [ ] Change predicates for Is Volume, Has Number, Contained in Journal properties #1241

**Comment by lsat12357** [comment]
acc to solr, there are no items in building-or that use tgn. There is one asset in gb-warner-nosatsu that uses tgn but it was soft-destroyed.

**Comment by jsimic** [comment]
@lsat12357 There are several other mass corrections that came out of the localCollectionName scrape. There are spreadsheets in the DigitalProjects/Metadata/OD2_Remediation/localCollectionName folder:
- Institution_changes.xlsx
- Missing_Identifiers.xlsx
- schnitzer-nitrate_dateChanges.xlsx
- Title_changes.xlsx

**Comment by lsat12357** [comment]
note was used in a bunch of colls by UO, see teams for scrapes.

**Comment by lsat12357** [comment]
additional spreadsheets from localCollName scrape are done.
